# Generated by Django 4.0.4 on 2022-05-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='tenure_type',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='tenure_type',
        ),
    ]
