# Generated by Django 4.0.4 on 2022-05-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_application_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
