# Generated by Django 4.0.4 on 2022-05-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bill_is_outstanding_bill_is_paid_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
