# Generated by Django 4.0.4 on 2022-05-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_offer_emi_paid_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='emi_paid_count',
            new_name='emi_passed_count',
        ),
    ]
