# Generated by Django 4.0.4 on 2022-05-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='gov_id_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='pan_card_num',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
