# Generated by Django 4.0.4 on 2022-05-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_gov_id_num_document_pan_card_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='account_no',
            new_name='account_number',
        ),
    ]
