# Generated by Django 4.0.4 on 2022-05-08 14:06

import core.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_account_no_bankaccount_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='gov_id',
            field=models.FileField(upload_to=core.models.Document.user_directory_path, validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='document',
            name='pan_card',
            field=models.FileField(upload_to=core.models.Document.user_directory_path, validators=[core.validators.validate_file_extension]),
        ),
    ]
