# Generated by Django 4.0.4 on 2022-05-09 16:01

import core.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_document_gov_id_alter_document_pan_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='gov_id',
            field=models.FileField(null=True, upload_to=core.models.Document.user_directory_path, validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='document',
            name='pan_card',
            field=models.FileField(null=True, upload_to=core.models.Document.user_directory_path, validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True),
        ),
    ]
