# Generated by Django 4.0.4 on 2022-05-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_document_gov_id_alter_document_pan_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='ctc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
